languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Alan Tanner"
logo = "logo.webp" 

[author]
name = "Alan Tanner"
image = "img/profilepic.png"
headline = "Software Engineer | using Xamarin, .NET, MSSQL"
bio = "Software Engineer"
links = [
  { linkedin = "https://linkedin.com/in/alanctanner" },
  { github = "https://github.com/alantanner" },
 # { youtube = "https://www.youtube.com/@alanctanner" },
  { dev = "https://dev.to/alanctanner" },
  { instagram = "https://www.instagram.com/alanctanner" },
  { email = "mailto:alan@alanctanner.com" }
]
dateFormat = "2 January 2006"